services:
  db:
    image: postgres:15
    container_name: finance_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=finance_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d finance_db"]
      interval: 3s
      timeout: 3s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: finance_app
    restart: always
    depends_on:
      db:
         condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      # Sobrescreve a URL do banco para apontar para o container 'db'
      - DATABASE_URL=postgresql://user:password@db:5432/finance_db

volumes:
  postgres_data:
